### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [trentrand/KarmaInfinity#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by trentrand** [comment]
Karan,

I have been working on adding proper documentation to all of my repositories.

Thanks for the suggestion, I have added the MIT license.

**Comment by karan** [comment]
Great. Thanks @trentrand
